# Interactive component

<script src="https://d3js.org/d3.v6.js"></script>
 <head> 
    <title>Id Attributes</title> 
    <style>  
        #business { 
            color:black; 
            font-size:14px; 
            font-weight:bold; 
            text-align:center; 
         } 
         #durableGoods { 
            color:black; 
            font-size:14px; 
            font-weight:bold; 
            text-align:center; 
         }
	#manufacturing { 
            color:black; 
            font-size:14px; 
            font-weight:bold; 
            text-align:center; 
         } 
	#nonDurableGoods { 
            color:black; 
            font-size:14px; 
            font-weight:bold; 
            text-align:center; 
         } 
 	#nonFinancial { 
            color:black; 
            font-size:14px; 
            font-weight:bold; 
            text-align:center; 
         } 
	#nonFarm { 
            color:black; 
            font-size:14px; 
            font-weight:bold; 
            text-align:center; 
         } 
	

    </style> 
</head> 
 <div id="plot"></div> 
 <p style="font-size: 24px"  class="fancy"> Choose your interested sectors </p>
 <p id="business" ><button type="button">Change to Business Sector</button></p>
 <p id="durableGoods"><button type="button">Change to Durable Goods Sector</button></p>
 <p id="manufacturing"><button type="button">Change to Manufacturing Sector</button></p>
 <p id="nonDurableGoods"><button type="button">Change to Non-durable Goods Sector</button></p>
 <p id="nonFinancial"><button type="button">Change to Non-financial Corporations Sector</button></p>
 <p id="nonFarm"><button type="button">Change to Non-farm Sector</button></p>
 
 <script src="scripts/interactive_bar.js"></script>
 
<p> 
The interactive bar graph shows the total number of Work From Home employees change in 2020 by month. 
Click on the buttons, we can explore that each sector has the lowest rate of Work From Home employees in October.
</p>